# Generated by Django 5.2.8 on 2025-11-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomamenities',
            options={'ordering': ['order'], 'verbose_name_plural': 'Amenities Categories'},
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='carapp.roomamenities')),
            ],
            options={
                'ordering': ['category__order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='carapp.amenity'),
        ),
    ]
