# Generated by Django 5.2.8 on 2025-11-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_alter_roomamenities_options_amenity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('total_guests', models.PositiveIntegerField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('additional_requirement', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('adult', models.PositiveIntegerField()),
                ('child', models.PositiveIntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.room')),
            ],
        ),
    ]
