# Generated by Django 5.2.8 on 2025-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_bookingform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='child',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
