# Generated by Django 5.2.8 on 2025-11-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_bookingform_child'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingForm',
            new_name='Booking',
        ),
    ]
