# Generated by Django 5.2.8 on 2025-11-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
